<?php $this->display("public/header.phtml");?>


<div id="main">
   
        <?php $this->display("public/menu.phtml");?>

        <div id="content">
                <div id="crumbs">
                                                       当前位置: <span>文章列表</span>
                </div>
                
                <div  id="search" >
                      <form action="/<?php echo ADMIN_NAME;?>/index/list/" method="get" class="search">
					    <p>
					        搜索:
					        <input type="text" value="<?php 
					        if(isset($_GET['search']) && $_GET['search']){
					            echo $_GET['search'];
					        }
					        ?>" style="width:250px;" name="search">
					        &nbsp;&nbsp;&nbsp;&nbsp;
					        <input type="submit" value="提交" class="button">
					    </p>
					</form>
                </div>
                
                <?php 
                
                 if(isset($data)){
                     	
                ?>
                 <table class="table">
                  <thead>
                    <tr>
                     
                      <th>标题</th>
                      <th>作者</th>
                    
                    
                      <th>分类目录</th>
                       <th>日期</th>
                    </tr>
                  </thead>
                  <tbody>

		            <?php 
		            
		               foreach($data as $row){
		            
		            ?>
			                    <tr>
			                    
			                      <td  style="text-align: left" ><a href="/<?php echo ADMIN_NAME?>/index/post/id/<?php echo $row['ID']?>"><?php echo $row['post_title']?></a> 
			                  
			                      </td>
			                      <td><?php echo getAuthor(1);?></td>
			                      
			                      <td> 
			                      <?php 
			                           
			                      $ArrCat =  getCategory($row['ID']);
			                      
			                      foreach($ArrCat as $r){
			                      
			                      ?>
			                      
			                           <a rel="category tag" title="<?php echo $r['name']?>" href="/Index/index/category/id/<?php echo $r['term_id']?>"><?php echo $r['name']?></a>,
			                     <?php 
			                      }
			                      
			                      ?> 
			                      </td>
			                       <td><?php echo $row['post_date']?></td>
			                       <td>
			                       
			                           <a href="/<?php echo ADMIN_NAME?>/index/post/id/<?php echo $row['ID']?>">[ 编辑 ]</a> / 
			                           <a href="/<?php echo ADMIN_NAME?>/index/del/id/<?php echo $row['ID']?>">[ 删除 ]</a> 
			                           
			                       </td>
			                    </tr>
                    
                      <?php 
		                  
		                  }
		                  
                      ?>  

              
                  </tbody>
                </table>
                
                
	            <?php 
	       
	                
	                
	            }else{
	            	
	            	echo "<div class='message'>暂无文章.</div>";
	            	
	            }
	            
	            ?>
			    
                
                 
            <?php 
            
            //分页
            if(isset($pages)){
            
            ?>
              <div class="pagination">
              
                 <?php 
                 
                 
                 echo $pages;
                 
                 ?>
                  
              </div>
            <?php 
       
            }
            
            ?>
                            
     </div>
      
     
    </div>
    
  <?php $this->display("public/footer.phtml");?>
