<?php $this->display("public/header.phtml");?>
    
<script type="text/javascript" charset="utf-8" src="<?php echo ADMIN_STATIC_PATH;?>js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo ADMIN_STATIC_PATH;?>js/ueditor/ueditor.all.min.js"> </script>
<!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
<!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
<script type="text/javascript" charset="utf-8" src="<?php echo ADMIN_STATIC_PATH;?>js/ueditor/lang/zh-cn/zh-cn.js"></script>


<div id="main">
        
       <?php $this->display("public/menu.phtml");?>
        <div id="content">
        
		                 <div id="crumbs">
		                                                       当前位置: <span>
                                                       <?php 
                                                       
                                                       
                                                       if(isset($id) && $id){
                                                       	
                                                       	   echo "编辑分类";
                                                       	
                                                       }else{
                                                       	  
                                                       	   echo "添加分类";
                                                       	
                                                       }
                                                       
                                                       ?>
                                                       </span> 
		                </div>
        
                        <form action="/<?php echo ADMIN_NAME;?>/index/postCategory/" method="post" >
                        
                        <div class="lefts">
                        
                         
                             <div class="input-w">
	                             
	                                     <input type="text" name="name" value="<?php if(isset($r) && $r['name']){ echo $r['name']; } ?>" class="post-title" placeholder="在此键入分类名称" /> 
                             </div>
  
                             <div class="input-w">
                             
                              <textarea rows="" placeholder="在此键入分类介绍" name="description"  cols="" class="textarea"><?php if(isset($r) && $r['description']){ echo $r['description']; } ?></textarea>
                              
                             </div>
                      
                         </div>
                         
                     
                         
                         <div class="input-w">

                                     <input type="submit" value="提交" class="post-button"/>

                         </div>
                         
                         <input type="hidden" name="action" value=" <?php 
                                                       
                                                       
                                                       if(isset($id) && $id){
                                                       	
                                                       	   echo "edit";
                                                       	
                                                       }else{
                                                       	  
                                                       	   echo "add";
                                                       	
                                                       }
                                                       
                                                       ?>">
                                                       
                         <input type="hidden" name="cat_id" value=" <?php echo isset($id) && $id?$id:0?>">
                         </form>
                         
                         </br>
                            
                            
       </div>

   
    </div>
    
  <?php $this->display("public/footer.phtml");?>