<?php 
 return array (
  'site_name' => 'Dean\'s Blog',
  'site_desc' => '专注底层开发的技术博客',
  'site_keywords' => 'YafBlog官网,yaf框架,PHP扩展,php内核,php博客程序',
  'descript' => 'Dean(blog.com)的博客. 主要分享PHP语言相关知识, PHP扩展, Zend引擎, PHP 内核的相关技术,记录在北京的故事. 以及记录对IT行业的思考和分析。',
  'domain' => 'http://blog.com/',
  'gzip' => '1',
  'charset' => 'utf-8',
  'timezone' => 'Etc/GMT-8',
  'template' => 'default',
  'admin_static_path' => 'http://blog.com/public/',
  'auth_key' => 'XuYNhghqgNfhUrsqE0VX',
  'cookie_domain' => '',
  'cookie_path' => '/',
  'cookie_pre' => 'KufRY_',
  'cookie_ttl' => '0',
  'session_storage' => 'files',
  'session_ttl' => '1800',
  'session_savepath' => 'sessions',
  'session_n' => '0',
  'memcache' => '127.0.0.1:11211',
  'auto_load_function' => '1',
);?>