
  <div id="footer">

        <p><a href="http://www.yafblog.com">YafBlog</a> &copy; Copyright 2014 - 由<strong>Yaf框架</strong>强力驱动</p>
        
        <p>Themes Design by <em>Yafblog</em>.Powered by Yafblog <?php echo VERSION?> &nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.miitbeian.gov.cn/">京ICP备14013467号</a> </p>  

        
      </div>
    </div>
	
	<div style="display: none;float: right;position:fixed; _position: absolute;" 
            id="go_top" class="go_top"><img  style="border-radius:3px;"  border="0" src="<?php echo STATIC_TEMPLATE_PATCH;?>img/top.png">
    </div>
	
	<div style="position: absolute;right: 0;top: 0;">
	     <img  style="border-radius:3px;"  border="0"  class="niao" src-bak="<?php echo STATIC_TEMPLATE_PATCH;?>" src="<?php echo STATIC_TEMPLATE_PATCH;?>img/niao.png">
	</div>
</body>

</html>
