<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>
后台管理 - 
<?php 

if(isset($r['post_title'])){
	echo $r['post_title'].'  - ';
}

echo load_config('system','site_name');

?>
 -  Powered by YafBlog!</title>
<link href="<?php echo ADMIN_STATIC_PATH;?>css/admin.css?v=001" rel="stylesheet" type="text/css" />
<script type="application/javascript" src="<?php echo ADMIN_STATIC_PATH;?>js/jquery-1.8.3.min.js"></script>
<script type="application/javascript" src="<?php echo ADMIN_STATIC_PATH;?>js/admin.js"></script>
</head>
<body>
      
    <div id="header">
    
              <div class="logo">
                               <img src="<?php echo ADMIN_STATIC_PATH;?>img/logo.png" alt="" />
              </div>
              
              <div class="mini_nav">
              <ul>
              
                   <li><a href="/<?php echo ADMIN_NAME?>/index/password"><span>[ 修改密码 ]</span></a> | </li> 
                   <li><a href="<?php echo load_config('system','domain')?>"><span>[ 返回首页 ]</span></a> | </li> 
                   <li><a href="/<?php echo ADMIN_NAME?>/login/logout"><span>[ 注销登录 ]</span></a> | </li> 
                  
              </ul>
              </div>
             
                   <?php 
	                
	                    $act  = $request = Yaf_Dispatcher::getInstance()->getRequest()->action;
	               
	               ?> 
              
        <div id="nav">
              <ul>
                   <li <?php 
		                        if(in_array($act,array('index'))){ 
		                    	   echo 'class="curr"';
		                        }
	                        ?> ><a href="/<?php echo ADMIN_NAME;?>/index/index" ><span>后台首页</span></a></li>
                   <li <?php 
		                        if(in_array($act,array('system'))){ 
		                    	   echo 'class="curr"';
		                        }
	                        ?> ><a href="/<?php echo ADMIN_NAME?>/index/system"><span>系统设置</span></a></li>
                  <!-- <li ><a href="/<?php echo ADMIN_NAME?>/index/template"><span>主题管理</span></a></li> -->
                   <li ><a href="http://www.yafblog.com"><span>官方网站</span></a></li>
              </ul>
        </div>
              
    </div>