<?php $this->display("public/header.phtml");?>
        
        <div id="content">
          
          <div class="post">
                  <?php 
                  
                  if(isset($r)){

                  ?>
	              <article class="article-content">
	          
	               <?php echo $r['post_content'];?>

	              </article>
	              
	                <div id="comment">
              
		                <!--高速版，加载速度快，使用前需测试页面的兼容性-->
		                <div id="SOHUCS"></div>
		                <script>
		                  (function(){
		                    var appid = 'cyr5CKxlz',
		                    conf = 'prod_3d43cb0230c4f1ab6b9700689a881ec5';
		                    var doc = document,
		                    s = doc.createElement('script'),
		                    h = doc.getElementsByTagName('head')[0] || doc.head || doc.documentElement;
		                    s.type = 'text/javascript';
		                    s.charset = 'utf-8';
		                    s.src =  'http://assets.changyan.sohu.com/upload/changyan.js?conf='+ conf +'&appid=' + appid;
		                    h.insertBefore(s,h.firstChild);
		                    window.SCS_NO_IFRAME = true;
		                  })()
		                </script>   
		              
		              </div>
              
              
                 <?php      
                  }else{
                  	    echo "<div class='message'>404</div>";
                  }
                  ?>
          </div>
          

           <?php $this->display("public/sidebar.phtml");?>
          
                     
        </div>
        
<?php $this->display("public/footer.phtml");?>